/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package one;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JFileChooser; 	 	
import javax.swing.JOptionPane; 	 	
import javax.swing.JPanel; 	 	
import javax.swing.JScrollPane; 	 	
import javax.swing.JTable; 	 	
import javax.swing.filechooser.FileNameExtensionFilter; 	 	
import java.util.Date; 	 	
import java.util.HashSet;
import java.util.List;
import java.util.Locale; 
import java.util.Set;
import com.sun.org.apache.xerces.internal.impl.xpath.regex.ParseException; 
import java.awt.BorderLayout; 	 	
import java.awt.CardLayout; 	 	
import java.io.File; 	 	
import java.text.DateFormat;
import java.text.SimpleDateFormat;
/**
 *
 * @author Rajeshwari
 */
public class AddPanel extends javax.swing.JPanel {
      /*Variable Declaration*/
        private MediaTableController mediaTableController; 
        private MediaTableModel mediaTableModel;
        private PeopleTableController peopleTableController; 
        private PeopleTableModel peopleTableModel;
        private JFileChooser fileChooser; 	 	
        private ProjectListTableController projectListTableController; 
        ProjectList projectAdd;
        int projectSelectedID = 0;
        int mediaID;
        Media tempMedia;
        Set<ProjectList> projectSet;
        Set<Media> mediaSet;
    /**
     * Creates new form AddPanel
     */
        public AddPanel() {
            initComponents();
            mediaTableController = new MediaTableController(this); 	 	
        } 	 	

        public AddPanel(int selectedID) {
            projectListTableController = new ProjectListTableController(this);
            projectAdd = projectListTableController.getProject(selectedID);
            this.projectSelectedID = selectedID;
            initComponents();
            mediaTableController = new MediaTableController(this);
        }

            /*Getter methods*/ 	 	
        public String getCategoryTextField(){ 	 	
            return categoryTextField.getText(); 	 	
        } 
        
        public String getProjectnameTextField(){ 	 	
            return projectNameTextField.getText(); 	 	
        } 	 	

        public String getStatusTextField(){ 	 	
            return Integer.toString(statusComboBox.getSelectedIndex()); 	 	
        } 	 	

        public String getResultTextArea(){ 	 	
            return resultTextArea.getText();         	 	
        } 	 	

        public String getStartDateChooser(){ 	 	
            return startDateChooser.getText(); 	 	
        } 	 	

        public String getEndDateChooser(){ 	 	
            return endDateChooser.getText(); 	 	
        } 	 	
	
        /*Add Media tablemodel to JTable*/        
        public void addMediaJtable() { 	 
            mediaTableController = new MediaTableController(this);
            // add a ListSelectionListener to the table 		    	
            filesTable.getSelectionModel().addListSelectionListener(mediaTableController);
            List<Media> result = mediaTableController.getMediaJtable(projectSelectedID);
            mediaTableModel = new MediaTableModel(result);				
            // add the data and column names to a JTable   	 	
            filesTable.setModel(mediaTableModel);		     	 	
        }
	/*Add People tablemodel to JTable*/    
        public void addPeopleJtable() { 	 
            peopleTableController = new PeopleTableController(this);
                // add a ListSelectionListener to the table 		    	
            peopleTable.getSelectionModel().addListSelectionListener(peopleTableController);
            List<PeopleList> result = peopleTableController.getPeopleJtable(projectSelectedID);
            peopleTableModel = new PeopleTableModel(result);				
            // add the data and column names to a JTable   	 	
            peopleTable.setModel(peopleTableModel);	    	 	 	
        }	
	     	 	
        public void updateMediaTable() { 	 	
            filesTable.setModel(mediaTableModel);
        }
            
        public void updatePeopleTable() {
            addPeopleJtable();		
        }

        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        projectnameLabel3 = new javax.swing.JLabel();
        categoryLabel3 = new javax.swing.JLabel();
        statusLabel3 = new javax.swing.JLabel();
        startdateLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        enddateLabel3 = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        categoryTextField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox();
        startDateChooser = new datechooser.beans.DateChooserCombo();
        endDateChooser = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        doneButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addfilesButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        filesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addpeopleButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        peopleTable = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(228, 221, 251));

        projectnameLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        projectnameLabel3.setText("Project Name");

        categoryLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        categoryLabel3.setText("Category");

        statusLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        statusLabel3.setText("Status");

        startdateLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        startdateLabel3.setText("Start Date");

        enddateLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        enddateLabel3.setText("End Date");

        projectNameTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        projectNameTextField.setActionCommand("null");

        categoryTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        categoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextFieldActionPerformed(evt);
            }
        });

        statusComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Completed", "Suspended", "Aborted" }));
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Result");

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane3.setViewportView(resultTextArea);

        doneButton.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(228, 222, 249));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Files");

        addfilesButton.setText("Browse");
        addfilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfilesButtonActionPerformed(evt);
            }
        });

        filesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File Name", "Type", "File Path"
            }
        ));
        jScrollPane2.setViewportView(filesTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                .addComponent(addfilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addfilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(228, 221, 251));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Add People");

        addpeopleButton.setText("Add People");
        addpeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpeopleButtonActionPerformed(evt);
            }
        });

        peopleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Company", "Email Address"
            }
        ));
        jScrollPane4.setViewportView(peopleTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(addpeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addpeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(projectnameLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enddateLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startdateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 349, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(300, 300, 300))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectnameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startdateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enddateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTextFieldActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
    	String[] arrayProject = new String[7];
    	arrayProject[0] = String.valueOf(projectSelectedID);
        arrayProject[1] = this.getProjectnameTextField();
        arrayProject[2] = this.getStatusTextField();
        arrayProject[3] = this.getStartDateChooser();
        arrayProject[4] = this.getEndDateChooser();
        arrayProject[5] = this.getCategoryTextField();
        arrayProject[6] = this.getResultTextArea();
        if(validateFeed()) {
             projectListTableController.updateRow(arrayProject); 
             JOptionPane.showMessageDialog(null, "Project added sucessfully.", "Add Project", JOptionPane.INFORMATION_MESSAGE);
             this.setVisible(false);
             JPanel mainPanel = (JPanel) this.getParent();
             CardLayout layout = (CardLayout) mainPanel.getLayout();
             SearchPanelAdmin addPanel = new SearchPanelAdmin();
             mainPanel.add(addPanel, "SeacrhAdmin");
             layout.show(mainPanel, "SeacrhAdmin");
        }        
    }//GEN-LAST:event_doneButtonActionPerformed

    private void addfilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfilesButtonActionPerformed
        // TODO add your handling code here:
        /*Create a file chooser*/
    	fileChooser = new JFileChooser();
        /*Create file filter to choose only JPEG and PNG*/
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF files and DOC files", "PDF", "DOC");
        fileChooser.setFileFilter(filter);
        fileChooser.setMultiSelectionEnabled(true);
        /*Create a dialog to open file from the disk*/
        int returnVal = fileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
	            /*Upload image using open browse window*/
	            File [] uploadFile = fileChooser.getSelectedFiles();
                    for (File f : uploadFile) { 
                        String[] arrayMedia = new String[filesTable.getColumnCount()];
                        arrayMedia[0] = f.getName();
                        arrayMedia[1] = f.getPath();
                        mediaID = mediaTableController.addRow(arrayMedia);
                        tempMedia = mediaTableController.getMedia(mediaID);
                        projectAdd = projectListTableController.getProject(projectSelectedID);
                        mediaSet = projectAdd.getRecordsMedia();
                        projectSet = tempMedia.getRecords();
                        mediaSet.add(tempMedia);
                        projectSet.add(projectAdd);
                        tempMedia.setRecords(projectSet);
                        projectAdd.setRecordsMedia(mediaSet);
                        projectListTableController.doPersist(projectAdd);
                        addMediaJtable();
                    }    
        }
    }//GEN-LAST:event_addfilesButtonActionPerformed

    private void addpeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpeopleButtonActionPerformed
                // TODO add your handling code here:
		PeopleViewGUI peopleView = new PeopleViewGUI(projectSelectedID, this);
                peopleView.setVisible(true);
    }//GEN-LAST:event_addpeopleButtonActionPerformed

    /*Validate the fields*/
    private boolean validateFeed() {
        boolean valid = true;
        if (this.getProjectnameTextField().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Project Name must not be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }

        else if (this.getCategoryTextField().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Category must not be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }

       else {         
            try {
                    Date startDate = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH).parse(this.getStartDateChooser());
                    Date endDate = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH).parse(this.getEndDateChooser());
                    if(startDate.compareTo(endDate) > 0) {
                            JOptionPane.showMessageDialog(null, "Start date shold be less than end date.", "Error", JOptionPane.ERROR_MESSAGE);
                valid = false;
                    }
            } catch (java.text.ParseException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
            }
        }		
        return valid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfilesButton;
    private javax.swing.JButton addpeopleButton;
    private javax.swing.JLabel categoryLabel3;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JButton doneButton;
    private datechooser.beans.DateChooserCombo endDateChooser;
    private javax.swing.JLabel enddateLabel3;
    private javax.swing.JTable filesTable;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable peopleTable;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JLabel projectnameLabel3;
    private javax.swing.JTextArea resultTextArea;
    private datechooser.beans.DateChooserCombo startDateChooser;
    private javax.swing.JLabel startdateLabel3;
    private javax.swing.JComboBox statusComboBox;
    private javax.swing.JLabel statusLabel3;
    // End of variables declaration//GEN-END:variables
}
