/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package one;
import java.awt.CardLayout;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Rajeshwari
 */
public class EditFormPanel extends javax.swing.JPanel {	
	private MediaTableController mediaTableController; 
	private MediaTableModel mediaTableModel;
	private PeopleTableController peopleTableController; 
	private PeopleTableModel peopleTableModel;
        private JFileChooser fileChooser; 	 	
	private ProjectListTableController projectListTableController; 
	ProjectList projectAdd;
	int projectSelectedID = 0;
	int mediaID;
	int peopleID;
	Media tempMedia;
	Set<ProjectList> projectSet;
	Set<Media> mediaSet;
    /**
     * Creates new form EditFormPanel
     */
    public EditFormPanel() {
        initComponents();
    }
    
    public EditFormPanel(int selectedID) {
    	projectListTableController = new ProjectListTableController(this);
    	ProjectList projectEdit = projectListTableController.getProject(selectedID);
    	this.projectSelectedID = selectedID;
    	initComponents();
    	projectnameTextField.setText(projectEdit.getName());
        categoryTextField.setText(projectEdit.getCategory());
        resultTextArea.setText(projectEdit.getResult());
        //endDateChooser.
        statusComboBox.setSelectedIndex(Integer.parseInt(projectEdit.getStatusNum())); 
        mediaTableController = new MediaTableController(this);
        addMediaJtable();
        addPeopleJtable();
    }
    
    public void addMediaJtable() { 	 
        mediaTableController = new MediaTableController(this);
        // add a ListSelectionListener to the table 		    	
        filesTable.getSelectionModel().addListSelectionListener(mediaTableController);
        List<Media> result = mediaTableController.getMediaJtable(projectSelectedID);
        mediaTableModel = new MediaTableModel(result);				
        // add the data and column names to a JTable   	 	
        filesTable.setModel(mediaTableModel);	 	
    }

    public void addPeopleJtable() { 	 
        peopleTableController = new PeopleTableController(this);
        // add a ListSelectionListener to the table 		    	
        peopleTable.getSelectionModel().addListSelectionListener(peopleTableController);
        List<PeopleList> result = peopleTableController.getPeopleJtable(projectSelectedID);
        peopleTableModel = new PeopleTableModel(result);				
        // add the data and column names to a JTable   	 	
        peopleTable.setModel(peopleTableModel);	 	 	
    }	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        projectnameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        startdateLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enddateLabel = new javax.swing.JLabel();
        projectnameTextField = new javax.swing.JTextField();
        categoryTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        statusComboBox = new javax.swing.JComboBox();
        startDateChooser = new datechooser.beans.DateChooserCombo();
        endDateChooser = new datechooser.beans.DateChooserCombo();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addfilesButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        filesTable = new javax.swing.JTable();
        deleteFileButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addpeopleButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        peopleTable = new javax.swing.JTable();
        deletePeopleButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(228, 221, 251));

        projectnameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        projectnameLabel.setText("Project Name");

        categoryLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        categoryLabel.setText("Category");

        statusLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        statusLabel.setText("Status");

        startdateLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        startdateLabel.setText("Start Date");

        enddateLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        enddateLabel.setText("End Date");

        projectnameTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N

        categoryTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        categoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Result");

        doneButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        doneButton.setText("Done");
        doneButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        statusComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Completed", "Suspended", "Aborted" }));
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(228, 221, 251));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Edit Files");

        addfilesButton.setText("Add File");
        addfilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfilesButtonActionPerformed(evt);
            }
        });

        filesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "File Name", "Type", "File Path"
            }
        ));
        jScrollPane3.setViewportView(filesTable);

        deleteFileButton.setText("Delete File");
        deleteFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteFileButton)
                .addGap(18, 18, 18)
                .addComponent(addfilesButton)
                .addContainerGap())
            .addComponent(jScrollPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addfilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(228, 221, 251));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Edit People");

        addpeopleButton.setText("Add People");
        addpeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpeopleButtonActionPerformed(evt);
            }
        });

        peopleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Company", "Email Address"
            }
        ));
        jScrollPane4.setViewportView(peopleTable);

        deletePeopleButton.setText("Delete People");
        deletePeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePeopleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletePeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(addpeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addpeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deletePeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
        );

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane2.setViewportView(resultTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(projectnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(categoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enddateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(startdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enddateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(442, 442, 442))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    /*Getter methods*/
    public String getCategoryTextField(){
        return categoryTextField.getText();
    }

    public String getProjectnameTextField(){
        return projectnameTextField.getText();
    }

    public String getStatusTextField(){
        return Integer.toString(statusComboBox.getSelectedIndex());
    }

    public String getResultTextArea(){
        return resultTextArea.getText();        
    }

    public String getStartDateChooser(){
        return startDateChooser.getText();
    }

    public String getEndDateChooser(){
    	return endDateChooser.getText();
    }

    private void categoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTextFieldActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
    	String[] arrayProject = new String[7];
    	arrayProject[0] = String.valueOf(projectSelectedID);
        arrayProject[1] = this.getProjectnameTextField();
        arrayProject[2] = this.getStatusTextField();
        arrayProject[3] = this.getStartDateChooser();
        arrayProject[4] = this.getEndDateChooser();
        arrayProject[5] = this.getCategoryTextField();
        arrayProject[6] = this.getResultTextArea();
        if(validateFeed()) {
        	projectListTableController = new ProjectListTableController(this);
	        projectListTableController.updateRow(arrayProject); 
	        JOptionPane.showMessageDialog(null, "Project updated sucessfully.", "Update Project", JOptionPane.INFORMATION_MESSAGE);
	        this.setVisible(false);
	        JPanel mainPanel = (JPanel) this.getParent();
	        CardLayout layout = (CardLayout) mainPanel.getLayout();
	        AddPanel addPanel = new AddPanel();
	        SearchPanelAdmin searchAdminPanel = new SearchPanelAdmin();
	        mainPanel.add(searchAdminPanel, "SearchAdminPanel");
	        layout.show(mainPanel, "SearchAdminPanel");
        } 
        
    }//GEN-LAST:event_doneButtonActionPerformed
    
    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void addfilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfilesButtonActionPerformed
        // TODO add your handling code here:
    	/*Create a file chooser*/
    	fileChooser = new JFileChooser();
        /*Create file filter to choose only JPEG and PNG*/
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF files and DOC files", "PDF", "DOC");
        fileChooser.setFileFilter(filter); 
        fileChooser.setMultiSelectionEnabled(true);
        /*Create a dialog to open file from the disk*/
        int returnVal = fileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
	            /*Upload image using open browse window*/
	            File [] uploadFile = fileChooser.getSelectedFiles();
                    for (File f : uploadFile) {  
                        String[] arrayMedia = new String[filesTable.getColumnCount()];
                        arrayMedia[0] = f.getName();
                        arrayMedia[1] = f.getPath();
                        mediaID = mediaTableController.addRow(arrayMedia);
                        tempMedia = mediaTableController.getMedia(mediaID);
                        projectAdd = projectListTableController.getProject(projectSelectedID);
                        mediaSet = projectAdd.getRecordsMedia();
                        projectSet = tempMedia.getRecords();
                        mediaSet.add(tempMedia);
                        projectSet.add(projectAdd);
                        tempMedia.setRecords(projectSet);
                        projectAdd.setRecordsMedia(mediaSet);
                        projectListTableController.doPersist(projectAdd);
                        addMediaJtable();
                  }  
        }   	
    }//GEN-LAST:event_addfilesButtonActionPerformed

    private void addpeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpeopleButtonActionPerformed
        // TODO add your handling code here:
    	PeopleViewGUI peopleView = new PeopleViewGUI(projectSelectedID,this);
    	peopleView.setVisible(true);
    }//GEN-LAST:event_addpeopleButtonActionPerformed

    private void deleteFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFileButtonActionPerformed
        // TODO add your handling code here:
		//get the project collection of media
    	int i;
        if((i = filesTable.getSelectedRow()) >= 0){
		    // get the mediaID from the selected row, first column		
		    mediaID = Integer.parseInt((String)filesTable.getValueAt(i,0));		
		    // get the project set from the media file, and the media set from the project
		    tempMedia = mediaTableController.getMedia(mediaID);
                    projectAdd = projectListTableController.getProject(projectSelectedID);
		    mediaSet = projectAdd.getRecordsMedia();
		    projectSet = tempMedia.getRecords();
		    // remove the respective elements if applicable
		    mediaSet.remove(tempMedia);
		    projectSet.remove(projectAdd);
		    tempMedia.setRecords(projectSet);
		    projectAdd.setRecordsMedia(mediaSet);
		    // persist and commit
		    mediaTableController.doRemove(tempMedia);
		    addMediaJtable();		    
	}
    }//GEN-LAST:event_deleteFileButtonActionPerformed

    private void deletePeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePeopleButtonActionPerformed
        // TODO add your handling code here:
    	PeopleList tempPeople;
        Set<PeopleList> peopleSet;
        int i;
        if((i = peopleTable.getSelectedRow()) >= 0){
		    // get the people from the selected row, first column		
		    peopleID = Integer.parseInt((String)peopleTable.getValueAt(i,0));		
		    // get the project set from the people file, and the people set from the project		
		    projectAdd = projectListTableController.getProject(projectSelectedID);		
		    tempPeople = peopleTableController.getPeople(peopleID);		
		    peopleSet = projectAdd.getRecordsPeople();		
		    projectSet = tempPeople.getRecords();		
		    // remove the respective elements if applicable		
		    peopleSet.remove(tempPeople);		
		    projectSet.remove(projectAdd);		
		    tempPeople.setRecords(projectSet);		
		    projectAdd.setRecordsPeople(peopleSet);		
		    // persist and commit		
		    peopleTableController.doRemove(tempPeople);
		    addPeopleJtable();
	}
    }//GEN-LAST:event_deletePeopleButtonActionPerformed

    /*Validate the fields*/
    private boolean validateFeed() {
        boolean valid = true;
        if (this.getProjectnameTextField().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Project Name must not be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }

        else if (this.getCategoryTextField().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Category must not be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }

       else {         
            try {
                    Date startDate = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH).parse(this.getStartDateChooser());
                    Date endDate = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH).parse(this.getEndDateChooser());
                    if(startDate.compareTo(endDate) > 0) {
                            JOptionPane.showMessageDialog(null, "Start date shold be less than end date.", "Error", JOptionPane.ERROR_MESSAGE);
                valid = false;
                    }
            } catch (java.text.ParseException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
            }
        }		
        return valid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfilesButton;
    private javax.swing.JButton addpeopleButton;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JButton deleteFileButton;
    private javax.swing.JButton deletePeopleButton;
    private javax.swing.JButton doneButton;
    private datechooser.beans.DateChooserCombo endDateChooser;
    private javax.swing.JLabel enddateLabel;
    private javax.swing.JTable filesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable peopleTable;
    private javax.swing.JLabel projectnameLabel;
    private javax.swing.JTextField projectnameTextField;
    private javax.swing.JTextArea resultTextArea;
    private datechooser.beans.DateChooserCombo startDateChooser;
    private javax.swing.JLabel startdateLabel;
    private javax.swing.JComboBox statusComboBox;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
	
    
    public void updatePeopleTable() {
    	addPeopleJtable();
		
    }
}
