/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package one;
import java.awt.BorderLayout;
import java.util.Set;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.JScrollPane;
import javax.swing.JTable;
/**
 *
 * @author sagarnaware
 */
public class PeopleViewGUI extends javax.swing.JFrame {
        // Variable Declaration
        private PeopleTableController peopleTableController;
        private PeopleTableModel peopleTableModel;
        private ProjectListTableController projectListTableController;
        int peopleSelectedID = 0;
        ProjectList projectAdd;
	int projectSelectedID = 0;
	PeopleList tempPeople;
	EditFormPanel editFormPanel;
        AddPanel addPanel;
	Set<ProjectList> projectSet;
	Set<PeopleList> peopleSet;
    /**
     * Creates new form PeopleViewGUI1
     */
    public PeopleViewGUI() {
        initComponents();
        this.setResizable(false);
        this.setSize(660, 575);
	peopleTableController = new PeopleTableController(this);
        peopleTable.setModel(peopleTableController.getTableModel());
        peopleTable.getSelectionModel().addListSelectionListener(peopleTableController);
        //addPeopletable();
    }
	
	public PeopleViewGUI(int id) {
        initComponents();
        this.setSize(660, 575);
        this.setResizable(false);
        this.setTitle("Add People");
        peopleTableController = new PeopleTableController(this);
        peopleTable.setModel(peopleTableController.getTableModel());
        peopleTable.getSelectionModel().addListSelectionListener(peopleTableController);
        projectSelectedID = id;
        projectListTableController = new ProjectListTableController(this);
        //addPeopletable();
    }

    public PeopleViewGUI(int id, EditFormPanel e) {
        initComponents();
        this.setSize(660, 575);
        this.setResizable(false);
        this.setTitle("Add People");
        peopleTableController = new PeopleTableController(this);
        peopleTable.setModel(peopleTableController.getTableModel());
        peopleTable.getSelectionModel().addListSelectionListener(peopleTableController);
        projectSelectedID = id;
        projectListTableController = new ProjectListTableController(this);
        editFormPanel = e;
	}
    
    public PeopleViewGUI(int id, AddPanel a) {
        initComponents();
        this.setSize(660, 575);
        this.setResizable(false);
        this.setTitle("Add People");
        peopleTableController = new PeopleTableController(this);
        peopleTable.setModel(peopleTableController.getTableModel());
        peopleTable.getSelectionModel().addListSelectionListener(peopleTableController);
        projectSelectedID = id;
        projectListTableController = new ProjectListTableController(this);
        addPanel = a;
    }

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        companynameTextField = new javax.swing.JTextField();
        emailaddressTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        peopleTable = new javax.swing.JTable();
        addpeopleButton = new javax.swing.JButton();
        addtoprojectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(830, 607));

        jPanel1.setBackground(new java.awt.Color(228, 221, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel1.setPreferredSize(new java.awt.Dimension(830, 595));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setText("Company Name");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel4.setText("Email Address");

        firstnameTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        firstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextFieldActionPerformed(evt);
            }
        });

        lastnameTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextFieldActionPerformed(evt);
            }
        });

        companynameTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N

        emailaddressTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N

        peopleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Comapny", "Email Address"
            }
        ));
        jScrollPane1.setViewportView(peopleTable);

        addpeopleButton.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        addpeopleButton.setText("Create Person");
        addpeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpeopleButtonActionPerformed(evt);
            }
        });

        addtoprojectButton.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        addtoprojectButton.setText("Add To Project");
        addtoprojectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoprojectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(addpeopleButton))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstnameTextField)
                                    .addComponent(lastnameTextField)
                                    .addComponent(companynameTextField)
                                    .addComponent(emailaddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(addtoprojectButton)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companynameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailaddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addpeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addtoprojectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTextFieldActionPerformed

    private void lastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextFieldActionPerformed

    private void addpeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpeopleButtonActionPerformed
        // TODO add your handling code here:
		String[] arrayPeople = new String[peopleTable.getColumnCount()];
                arrayPeople[0] = firstnameTextField.getText();
                arrayPeople[1] = lastnameTextField.getText();
                arrayPeople[2] = companynameTextField.getText();
                arrayPeople[3] = emailaddressTextField.getText();
                peopleSelectedID = peopleTableController.addRow(arrayPeople); 
                addPeopletable();
    }//GEN-LAST:event_addpeopleButtonActionPerformed

    private void addtoprojectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoprojectButtonActionPerformed
        // TODO add your handling code here:
		peopleSelectedID = peopleTableController.rowNumberSelected();
		tempPeople = peopleTableController.getPeople(peopleSelectedID);
		projectAdd = projectListTableController.getProject(projectSelectedID);
		peopleSet = projectAdd.getRecordsPeople();
		projectSet = tempPeople.getRecords();
		peopleSet.add(tempPeople);
		projectSet.add(projectAdd);
		tempPeople.setRecords(projectSet);
		projectAdd.setRecordsPeople(peopleSet);
		projectListTableController.doPersist(projectAdd);
		if (editFormPanel != null){
			editFormPanel.updatePeopleTable();
		}
		else if (addPanel != null) {
			addPanel.updatePeopleTable();
		}
    }//GEN-LAST:event_addtoprojectButtonActionPerformed
    
    public void addPeopletable() { 	 	
	// add the data and column names to a JTable   	 	
    	peopleTable.setModel(peopleTableController.getTableModel());		 	 	
	// add a ListSelectionListener to the table 	 	
    	peopleTable.getSelectionModel().addListSelectionListener(peopleTableController); 	 	
    } 	 	
     	 	
    public void updateTable() { 	 	
    	peopleTable.setModel(peopleTableController.getTableModel());
    }
    
    // display data on the nameTextField
    public void setFirstNameTextField(String value) {
    	firstnameTextField.setText(value);
    }
    
    // display data on the courseNumberTextField
    public void setLastNameTextField(String value) {
    	lastnameTextField.setText(value);
    }
    
    // display data on the enrollmentTextField
    public void setCompanayNameTextField(String value) {
    	companynameTextField.setText(value);
    }
    
    // display data on the startDateTextField
    public void setEmailAddressTextField(String value) {
    	emailaddressTextField.setText(value);
    }
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleViewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpeopleButton;
    private javax.swing.JButton addtoprojectButton;
    private javax.swing.JTextField companynameTextField;
    private javax.swing.JTextField emailaddressTextField;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTable peopleTable;
    // End of variables declaration//GEN-END:variables
}
