/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package one;

import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author sagarnaware
 */
public class SearchPanelViewer extends javax.swing.JPanel {
	private ProjectListTableController projectListTableController;
        private ProjectListTableModel projectListTableModel;

    /**
     * Creates new form SearchPanelViewer1
     */
    public SearchPanelViewer() {
        initComponents();
        searchprojectTable.addMouseListener(new MouseAdapter(){                
   	     public void mouseClicked(MouseEvent e){
                 System.out.println("   ");
   	         if (e.getClickCount() == 2){
   	            JTable target = (JTable)e.getSource();
   	            int rowSelected = projectListTableController.rowNumberSelected();
   	            ProjectDetailsPanel projectDetailsPanel = new ProjectDetailsPanel(rowSelected);
   	            projectDetailsPanel.setVisible(true);
   	         }
   	     	}
    	});
        dateCheckBox.setSelected(true);
        statusCheckBox.setSelected(true);
        peopleCheckBox.setSelected(true);
	endDateChooser.setVisible(true);
        startDateChooser.setVisible(true);
        statusField.setVisible(true);
        endDateLabel6.setVisible(true);
        startDateLabel.setVisible(true);
        statusLabel.setVisible(true); 
        peopleTextField.setVisible(true);
        
         
    }
    /*Getter*/
    public String getCategoryTextField(){
        return categoryTextField.getText();
    }

    public String getProjectnameTextField(){
        return nameTextField.getText();
    }

    public String getStatusTextField(){
        return Integer.toString(statusField.getSelectedIndex());
    }

    public String getStartDateChooser(){
        return startDateChooser.getText();
    }

    public String getEndDateChooser(){
    	return endDateChooser.getText();
    }
    
    public String getPersonName() {
    	return peopleTextField.getText();
    }
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchprojectTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        statusCheckBox = new javax.swing.JCheckBox();
        statusField = new javax.swing.JComboBox();
        statusLabel = new javax.swing.JLabel();
        dateCheckBox = new javax.swing.JCheckBox();
        startDateLabel = new javax.swing.JLabel();
        endDateChooser = new datechooser.beans.DateChooserCombo();
        endDateLabel6 = new javax.swing.JLabel();
        startDateChooser = new datechooser.beans.DateChooserCombo();
        peopleCheckBox = new javax.swing.JCheckBox();
        peopleTextField = new javax.swing.JTextField();
        gobackButton = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(228, 221, 251));

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nameLabel.setText("Project Name");

        nameTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        categoryLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        categoryLabel.setText("Category");

        categoryTextField.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        categoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextFieldActionPerformed(evt);
            }
        });

        searchprojectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project Id", "Name", "Status", "Start Date", "End Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(searchprojectTable);

        searchButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        searchButton.setText("Search Project");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(228, 221, 251));

        statusCheckBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        statusCheckBox.setText("Search By Status");
        statusCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCheckBoxActionPerformed(evt);
            }
        });

        statusField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statusField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Completed", "Suspended", "Aborted" }));
        statusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFieldActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        statusLabel.setText("Status");

        dateCheckBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        dateCheckBox.setText("Search By Date");
        dateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateCheckBoxActionPerformed(evt);
            }
        });

        startDateLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        startDateLabel.setText("Start Date");

        endDateLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        endDateLabel6.setText("End Date");

        peopleCheckBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        peopleCheckBox.setText("Search By People");
        peopleCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                peopleCheckBoxStateChanged(evt);
            }
        });
        peopleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleCheckBoxActionPerformed(evt);
            }
        });

        peopleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusCheckBox)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(peopleCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateCheckBox)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCheckBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endDateLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(peopleCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peopleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        gobackButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        gobackButton.setText("Go Back");
        gobackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackButtonMouseClicked(evt);
            }
        });
        gobackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(gobackButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(categoryLabel)
                        .addGap(69, 69, 69)
                        .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gobackButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
		try {
			Date startDateTemp = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH).parse(this.getStartDateChooser());
			Date endDateTemp = new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH).parse(this.getEndDateChooser());
			java.sql.Date startDate = new java.sql.Date(startDateTemp.getTime());
			java.sql.Date endDate = new java.sql.Date(endDateTemp.getTime());
			String nameProject = this.getProjectnameTextField();
                        String categoryProject = this.getCategoryTextField();
                        String statusField = this.getStatusTextField();
                        String personName = this.getPersonName();
                        List<ProjectList> result = null;
                        projectListTableController = new ProjectListTableController(this);
			if(dateCheckBox.isSelected() && statusCheckBox.isSelected()&& peopleCheckBox.isSelected()) {
				result = projectListTableController.searchQueryViewerDSP(startDate, endDate, nameProject, categoryProject, statusField, personName);
                        }
			else if(!dateCheckBox.isSelected() && statusCheckBox.isSelected() && !peopleCheckBox.isSelected()) {
				result = projectListTableController.searchQueryViewerS(nameProject, categoryProject, statusField);
                        }
			else if(dateCheckBox.isSelected() && !statusCheckBox.isSelected() && !peopleCheckBox.isSelected()) {
                                result = projectListTableController.searchQueryViewerD(startDate, endDate, nameProject, categoryProject);
			}
                        else if(dateCheckBox.isSelected() && statusCheckBox.isSelected() && !peopleCheckBox.isSelected()) {
				result = projectListTableController.searchQueryViewerDS(startDate, endDate, nameProject, categoryProject, statusField);
                        }
                        else if(dateCheckBox.isSelected() && !statusCheckBox.isSelected()&& peopleCheckBox.isSelected()) {
				result = projectListTableController.searchQueryViewerDP(startDate, endDate, nameProject, categoryProject, personName);
                        }
                        else if(!dateCheckBox.isSelected() && statusCheckBox.isSelected()&& peopleCheckBox.isSelected()) {
				result = projectListTableController.searchQueryViewerSP(nameProject, categoryProject, statusField, personName);
                        }
                        else if(!dateCheckBox.isSelected() && !statusCheckBox.isSelected()&& peopleCheckBox.isSelected()) {
                                result = projectListTableController.searchQueryViewerP( nameProject, categoryProject, personName);
                        }
			else if(!dateCheckBox.isSelected() && !statusCheckBox.isSelected()&& !peopleCheckBox.isSelected()) {
				result = projectListTableController.searchQueryViewer(nameProject, categoryProject);
                        }
			projectListTableModel = new ProjectListTableModel(result);				
			addProjectJtable();
    	} catch (java.text.ParseException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
    	}
    }//GEN-LAST:event_searchButtonActionPerformed
	
	public void addProjectJtable() {
            // add the data and column names to a JTable  
            searchprojectTable.setModel(projectListTableModel);
            // add a ListSelectionListener to the table 
            projectListTableController = new ProjectListTableController(projectListTableModel, this);
            searchprojectTable.getSelectionModel().addListSelectionListener(projectListTableController);
           
//            searchprojectTable.addMouseListener(new MouseAdapter(){                
//   	     public void mouseClicked(MouseEvent e){
//                 System.out.println("   ");
//   	         if (e.getClickCount() == 3){
//   	            JTable target = (JTable)e.getSource();
//   	            int rowSelected = projectListTableController.rowNumberSelected();
//   	            ProjectDetailsPanel projectDetailsPanel = new ProjectDetailsPanel(rowSelected);
//   	            projectDetailsPanel.setVisible(true);
//   	         }
//   	     	}
//    	});
	}	
    private void dateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateCheckBoxActionPerformed
        // TODO add your handling code here:
        if(!dateCheckBox.isSelected()) {
            endDateChooser.setVisible(false);
            startDateChooser.setVisible(false);
            endDateLabel6.setVisible(false);
            startDateLabel.setVisible(false);
        }
        if(dateCheckBox.isSelected()) {
            endDateChooser.setVisible(true);
            startDateChooser.setVisible(true);
            endDateLabel6.setVisible(true);
            startDateLabel.setVisible(true);
        }    
    }//GEN-LAST:event_dateCheckBoxActionPerformed

    private void categoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTextFieldActionPerformed

    private void statusCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCheckBoxActionPerformed
        // TODO add your handling code here:
	if(statusCheckBox.isSelected()) {
	    	statusField.setVisible(true); 
	    	statusLabel.setVisible(true);
            
    	}
    	if(!statusCheckBox.isSelected()) {
	    	statusField.setVisible(false); 
	    	statusLabel.setVisible(false);
        }
    }//GEN-LAST:event_statusCheckBoxActionPerformed

    private void gobackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gobackButtonMouseClicked

    private void gobackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackButtonActionPerformed
        // TODO add your handling code here:
    	this.setVisible(false);
        JPanel mainPanel = (JPanel) this.getParent();
        CardLayout layout = (CardLayout) mainPanel.getLayout();
        WelcomePanel welcomePanel = new WelcomePanel();
        mainPanel.add(welcomePanel, "WelcomePanel");
        layout.show(mainPanel, "WelcomePanel");
    }//GEN-LAST:event_gobackButtonActionPerformed

    private void peopleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peopleCheckBoxActionPerformed
        // TODO add your handling code here:
    	if(peopleCheckBox.isSelected()) {
                //peopleTextField.setLocation(5, 5);
                peopleTextField.setVisible(true); 
                
                peopleTextField.revalidate();
	    }
    	if(!peopleCheckBox.isSelected()) {
                peopleTextField.setVisible(false);
                
	    }
    }//GEN-LAST:event_peopleCheckBoxActionPerformed

    private void peopleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peopleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peopleTextFieldActionPerformed

    private void peopleCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_peopleCheckBoxStateChanged
        // TODO add your handling code here:
//        if(peopleCheckBox.isSelected()) {
//                peopleTextField.setVisible(true);               
//                peopleTextField.repaint();
//	    }
//    	if(!peopleCheckBox.isSelected()) {
//                peopleTextField.setVisible(false);
//                
//	    }
    }//GEN-LAST:event_peopleCheckBoxStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JCheckBox dateCheckBox;
    private datechooser.beans.DateChooserCombo endDateChooser;
    private javax.swing.JLabel endDateLabel6;
    private javax.swing.JButton gobackButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JCheckBox peopleCheckBox;
    private javax.swing.JTextField peopleTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable searchprojectTable;
    private datechooser.beans.DateChooserCombo startDateChooser;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JCheckBox statusCheckBox;
    private javax.swing.JComboBox statusField;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
